"""Add is_read field to receipts

Revision ID: 0c409722fe1e
Revises: e89b8c6e28bb
Create Date: 2025-07-27 00:37:34.899864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c409722fe1e'
down_revision: Union[str, None] = 'e89b8c6e28bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('is_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'is_read')
    # ### end Alembic commands ###
